services:
  frontend:
    image: frontend
    environment:
      - API_URL=http://localhost:8080/api

  backend:
    image: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    container_name: redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /home/hernan/Docker/2.8-exercise/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
