services:
  frontend:
    image: frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    container_name: redis

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
